#docker-compose.yml
version: "3.8"

services:
    php:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        ports:
          - "8000:8000"
        volumes:
            - .:/app/
        networks:
            - symfony

    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
        ports:
          - "80:80"
        volumes:
          - .:/app/
        links:
          - php
          - database
        networks:
            - symfony
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"
        networks:
          - symfony
  ###> doctrine/doctrine-bundle ###
    database:
      build:
          context: .
          dockerfile: docker/db/DockerFile
      restart: always
      ports:
        - 5432:5432
      healthcheck:
        test: ["CMD", "pg_isready"]
        timeout: 5s
        retries: 5
        start_period: 60s
      volumes:
        - ./docker/postgres/:/docker-entrypoint-initdb.d/
      networks:
        - symfony
  ###< doctrine/doctrine-bundle ###

networks:
    symfony:
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
